function [s5] = cOOKieFilter(Fs, N, Fpass, Fstop, sMin, sMax, FileName) 
% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 13-Jul-2016 11:00:58

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
% Fs = 8000000;  % Sampling Frequency

% N     = 128;      % Order
% Fpass = 93750;   % Passband Frequency
% Fstop = 750000;  % Stopband Frequency
Wpass = 1;       % Passband Weight
Wstop = 1;       % Stopband Weight
dens  = 20;      % Density Factor

% Calculate the coefficients using the FIRPM function.
bb  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ... 
           {dens});
Hd = dfilt.dffir(bb);

% 8 MHz sample rate
% Nyquist = 4 MHz
signal = load_sc16q11(FileName);
s2 = abs(signal);
s3 = filter(Hd,s2);
s4 = filter(Hd,s3);
s5 = max(sMin,min(sMax,s4));
plot(s5);
